# Environment
language: cpp

compiler:
  - gcc

# Install build dependencies
before_script:
  - sudo apt-get install cmake libboost-all-dev libreadline6-dev libprotobuf-dev libsnappy-dev
  
  # TrisDB requires GCC > 4.7
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

  # TrisDB requires Boost >= 1.48
  - sudo apt-add-repository ppa:jkeiren/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.48-all-dev

# Build script
script:
  - cd build/
  - cmake ../src/
  - make -j 3

notifications:
  # Email commit author only on build status change
  email:
    on_success: change
    on_failure: always

os:
  - linux
